# Generated by Django 3.1.3 on 2020-11-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_auto_20201113_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='fcm_toke',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='students',
            name='fcm_toke',
            field=models.TextField(default=''),
        ),
    ]
